const fs = require("fs");
const path = require("path");
const {
  createUser,
  getAppleDisplayNameFallback,
  isAutoGeneratedAppleDisplayName,
} = require("../auth/authHelpers");

const USERS_PATH = path.join(__dirname, "..", "data", "users.json");

function ensureUsersFile() {
  fs.mkdirSync(path.dirname(USERS_PATH), { recursive: true });

  if (!fs.existsSync(USERS_PATH)) {
    fs.writeFileSync(USERS_PATH, JSON.stringify([], null, 2), "utf8");
  }
}

function readUsers() {
  ensureUsersFile();

  try {
    const raw = fs.readFileSync(USERS_PATH, "utf8");
    const parsed = raw ? JSON.parse(raw) : [];
    return Array.isArray(parsed) ? parsed : [];
  } catch (error) {
    return [];
  }
}

function writeUsers(users) {
  ensureUsersFile();
  fs.writeFileSync(USERS_PATH, JSON.stringify(Array.isArray(users) ? users : [], null, 2), "utf8");
}

function cloneUser(user) {
  return user && typeof user === "object" ? { ...user } : null;
}

function saveUserList(users) {
  writeUsers(users);
  return users;
}

function addUser(userInput) {
  const users = readUsers();
  const user = createUser(userInput);
  users.push(user);
  saveUserList(users);
  return cloneUser(user);
}

function getAllUsers() {
  return readUsers().map(cloneUser);
}

function findUserByProvider(provider, providerUserId) {
  return cloneUser(
    readUsers().find(
      (user) =>
        user.provider === provider && user.providerUserId === providerUserId
    ) || null
  );
}

function findUserById(userId) {
  return cloneUser(readUsers().find((user) => user.id === userId) || null);
}

function findUserByStripeCustomerId(stripeCustomerId) {
  if (!stripeCustomerId) {
    return null;
  }

  return cloneUser(
    readUsers().find((user) => user.stripeCustomerId === stripeCustomerId) || null
  );
}

function updateUser(userId, updater) {
  const users = readUsers();
  const index = users.findIndex((user) => user.id === userId);

  if (index === -1) {
    return null;
  }

  const currentUser = users[index];
  const nextUser = updater({ ...currentUser }) || currentUser;
  users[index] = nextUser;
  saveUserList(users);
  return cloneUser(nextUser);
}

function normalizeAppleUserProfile(user, userInput) {
  if (!user || user.provider !== "apple") {
    return;
  }

  const email = userInput && userInput.email ? userInput.email : user.email;
  const existingName = user.name && !isAutoGeneratedAppleDisplayName(user.name, email)
    ? user.name
    : null;
  const nextDisplayName = userInput && userInput.displayName
    ? userInput.displayName
    : (existingName || getAppleDisplayNameFallback(email));

  if (!user.displayName || isAutoGeneratedAppleDisplayName(user.displayName, email)) {
    user.displayName = nextDisplayName;
  }

  if (isAutoGeneratedAppleDisplayName(user.name, email)) {
    user.name = null;
  }
}

function findOrCreateUser(userInput) {
  const users = readUsers();
  const existingIndex = users.findIndex(
    (user) =>
      user.provider === userInput.provider &&
      user.providerUserId === userInput.providerUserId
  );

  if (existingIndex !== -1) {
    const existingUser = users[existingIndex];

    if (userInput.name !== undefined) {
      existingUser.name = userInput.name;
    }

    if (userInput.email !== undefined) {
      existingUser.email = userInput.email;
    }

    if (userInput.googleName !== undefined) {
      existingUser.googleName = userInput.googleName || existingUser.googleName || null;
    }

    if (userInput.googlePicture !== undefined) {
      existingUser.googlePicture = userInput.googlePicture || existingUser.googlePicture || null;
    }

    if (userInput.googleTokens !== undefined) {
      existingUser.googleTokens = userInput.googleTokens || existingUser.googleTokens || null;
    }

    if (userInput.displayName !== undefined) {
      if (existingUser.provider === "apple") {
        if (
          !existingUser.displayName ||
          isAutoGeneratedAppleDisplayName(existingUser.displayName, existingUser.email || userInput.email)
        ) {
          existingUser.displayName = userInput.displayName || existingUser.displayName || null;
        }
      } else {
        existingUser.displayName = userInput.displayName || existingUser.displayName || null;
      }
    }

    if (userInput.avatarUrl !== undefined) {
      existingUser.avatarUrl = userInput.avatarUrl || existingUser.avatarUrl || null;
    }

    if (userInput.theme !== undefined) {
      existingUser.theme = userInput.theme || existingUser.theme || "system";
    }

    if (existingUser.provider === "google") {
      if (!existingUser.googleName && existingUser.name) {
        existingUser.googleName = existingUser.name;
      }

      if (!existingUser.googlePicture && userInput.avatarUrl && !userInput.displayName) {
        existingUser.googlePicture = userInput.avatarUrl;
      }
    }

    normalizeAppleUserProfile(existingUser, userInput);

    saveUserList(users);
    return cloneUser(existingUser);
  }

  const nextUserInput = { ...userInput };

  if (nextUserInput.provider === "apple") {
    nextUserInput.displayName = nextUserInput.displayName || getAppleDisplayNameFallback(nextUserInput.email);
  }

  const user = createUser(nextUserInput);
  users.push(user);
  saveUserList(users);
  return cloneUser(user);
}

function updateUserSettings(userId, settings) {
  return updateUser(userId, (user) => {
    if (settings.displayName !== undefined) {
      user.displayName = settings.displayName || null;
    }

    if (settings.avatarUrl !== undefined) {
      user.avatarUrl = settings.avatarUrl || null;
    }

    if (settings.theme !== undefined) {
      user.theme = settings.theme || "system";
    }

    return user;
  });
}

function updateUserGoogleTokens(userId, googleTokens) {
  return updateUser(userId, (user) => {
    user.googleTokens = googleTokens || null;
    return user;
  });
}

function updateUserStripeBilling(userId, billing) {
  return updateUser(userId, (user) => {
    user.stripeCustomerId = billing && billing.stripeCustomerId ? billing.stripeCustomerId : user.stripeCustomerId || null;
    user.stripeSubscriptionId = billing && Object.prototype.hasOwnProperty.call(billing, "stripeSubscriptionId")
      ? billing.stripeSubscriptionId
      : (user.stripeSubscriptionId || null);
    user.stripeSubscriptionStatus = billing && Object.prototype.hasOwnProperty.call(billing, "stripeSubscriptionStatus")
      ? billing.stripeSubscriptionStatus
      : (user.stripeSubscriptionStatus || null);
    user.stripePriceId = billing && Object.prototype.hasOwnProperty.call(billing, "stripePriceId")
      ? billing.stripePriceId
      : (user.stripePriceId || null);
    user.billingInterval = billing && Object.prototype.hasOwnProperty.call(billing, "billingInterval")
      ? billing.billingInterval
      : (user.billingInterval || null);

    if (billing && Object.prototype.hasOwnProperty.call(billing, "plan")) {
      user.plan = billing.plan === "pro" ? "pro" : "free";
    }

    return user;
  });
}

function getUserGoogleTokens(userId) {
  const user = findUserById(userId);
  return user && user.googleTokens ? user.googleTokens : null;
}

module.exports = {
  addUser,
  findUserById,
  findUserByProvider,
  findUserByStripeCustomerId,
  findOrCreateUser,
  getUserGoogleTokens,
  getAllUsers,
  updateUserGoogleTokens,
  updateUserSettings,
  updateUserStripeBilling,
};
